### ISSUE TITLE
Temporary file creation

### ISSUE THREAD

**Issue by pun-ky** [jcgay/send-notification#10]
When I have integrated this notifier into Gradle plugin, there is being created a file named "null" (on CWD) with contents "Active code page: 1250". This is annoying for my plugin users, because this file is created under directory using VCS.  

Now I am forced to remove that file manually, even just after `Notifier.close()` (it is not cleaning :/)

Environment: Windows 10, 64-bit
Send-notification: 0.14.0
Java: 8

**Comment by pun-ky** [comment]
one extra question, I specified an application name but still seeing on Windows "Java Platform" in the bottom of notification. I have no idea how  to override it. Is it even possible? I was thinking that `Application` is for that case exactly...

**Comment by jcgay** [comment]
Huum I have no idea what's this file is :(
Which notifier are you using ?

**Comment by pun-ky** [comment]
Default for Windows 10. I don't know exactly which one is it. Looks like native

**Comment by jcgay** [comment]
I have just tried to reproduce it (with this [VM](https://github.com/jcgay/send-notification/tree/master/send-notification-cli/src/vm/windows)), but I don't (I'm not using `Windows` myself 😓)...

I have launched `send-notification` with its CLI, or with `Maven` (via [maven-notifier](https://github.com/jcgay/maven-notifier)) without luck. I don't find a `null` file created in the current directory.  

Maybe I do something wrong ?

Is this this kind of notification you see ?
![notification](https://user-images.githubusercontent.com/967336/44955219-2c915800-aeb0-11e8-8f57-1b808aab4bd9.PNG)

I have noticed the `Java Platform` thingy too (might have appeared with Windows 10), not sure if I can remove it, I'll have a look.

**Comment by withparadox2** [comment]
I use `apply plugin: 'fr.jcgay.gradle-notifier'`, get a null file every time after I sync android project. 

Environment: Windows 7, 64-bit
gradle-notifier 1.2.0
Java: 8

**Comment by jcgay** [comment]
Ok thanks.
I'll give it another try with gradle 😕

**Comment by jcgay** [comment]
I think I have been able to reproduce it.

It seems to appear when trying to find [BurntToast](https://github.com/Windos/BurntToast).
I have a `null` file created with content:

    Active code page: 1252

To prevent it at the moment, you can choose a working notifier by configuration instead of letting `send-notification` choose one for you.

For gradle it would be:

    notifier {
        implementation = 'systemtray'
    }

**Comment by withparadox2** [comment]
@jcgay Thank you, it does work!

**Comment by jcgay** [comment]
And this is an issue with [jPowershell](
https://github.com/profesorfalken/jPowerShell) : https://github.com/profesorfalken/jPowerShell/issues/33  

It should be fixed in `send-notification` next release.

**Comment by pun-ky** [comment]
Thanks!

**Comment by pun-ky** [comment]
What is ETA for next release?

**Comment by jcgay** [comment]
It is released as `v0.15.0`, can you check that it is ok for you ?

@withparadox2 I have also released `gradle-notifier` v3.0.0
