### ISSUE TITLE
BurntToast causes auto-detect to be very slow on Windows

### ISSUE THREAD

**Issue by seanf** [jcgay/send-notification#18]
I found `maven-notifier` to be very slow on Windows 10 with default configuration (ie no config). Maven commands which had taken about 1 second started taking about 10 seconds, and I eventually traced it to `BurntToastNotifier.tryInit`. (I didn't have BurntToast installed.)

I just installed BurntToast to see if `Get-Module -ListAvailable -Name BurntToast | Format-Table Name` could detect it faster, and I think it's far too slow to activate automatically.

Would you accept a PR to remove BurntToast from the automatic detection in `NotifierProvider.available()`?

**Comment by jcgay** [comment]
Sure if it's that slow, it should be removed from the discoverable candidate 😇
If you need any help for the PR, don't hesitate to ping me.
Thanks
