### ISSUE TITLE
Support multiple notifications

### ISSUE THREAD

**Issue by rnc** [jcgay/send-notification#4]
It would be useful to support multiple notifications e.g.

`notifier.implementation=kdialog,pushbullet`

Also, does the extension log information anywhere?

**Comment by jcgay** [comment]
It would be great indeed, I'll add it :+1: 

`send-notification` by itself use SLF4J for logging, so you can configure logging the way you want.
As you're talking about extension, I guess you came from [`maven-notifier`](https://github.com/jcgay/maven-notifier) ? If so, logging is configured by Maven. You can have debug information using `-X` option.

**Comment by rnc** [comment]
Re debug - yes sorry about that, just realised when running with `-X` :-)

Re multiple notifications - being able to dynamically configure would be an interesting use case. For instance - normally when working at the computer I might just choose to have `kdialog` configured. If I set off a long running build, I might (also) want `pushbullet` enabled.

**Comment by alexcreasy** [comment]
Yes, I would love this feature! It really be really nice to be able to set a semi-intrusive notification as "always on", for me this would be notify-send, but also have the option of manually asking for a very-intrusive notification, for me pushbullet.

The idea being that most of the time I'm at my desk during the build and will only alt-tab back when I get the popup, I don't need everything I own lighting up. However, if I'm running a full test suite, I might want to step away for coffee. In this case it would be nice to be able to specify a pushbullet notification with, say, an extra maven argument, so I can relax knowing that if I've done something stupid I'll get notified and won't lose 15 minutes :)

**Comment by jcgay** [comment]
Yep got it, I faced the same kind of situation but end with a slightly different solution by adding a way to override/set configuration at runtime.
What you can already do is set `-DnotifyWith=pushbullet` when launching a long build. But it will not send notification with your primary notifier.

I'll add a way to use multiple notifiers when a property is set, this is a nice idea !

**Comment by jcgay** [comment]
I have build a maven-notifier SNAPSHOT with a first implementation at https://oss.sonatype.org/content/repositories/snapshots/fr/jcgay/maven/maven-notifier/1.6-SNAPSHOT/
(Error reporting is kind of missing right now)

Could you give it a try to see if it fits your needs ?

To active the new mechanism you'll have to give maven the property `notifyAll` and separate notifier implementations by `,` in `notifier.implementation`.

```
notifier.implementation = growl,pushbullet

mvn install -DnotifyAll
```

**Comment by rnc** [comment]
+1 ... looks great :-)

**Comment by alexcreasy** [comment]
+1 here too, it works great thanks!

**Comment by jcgay** [comment]
Cool, I will release it soon.
Thanks for the feedback !
