### ISSUE TITLE
Why make Application mandatory

### ISSUE THREAD

**Issue by tomsquest** [jcgay/send-notification#7]
As a developer,
When I want to send a notification from my app,
Then I need to provide both an  `Application` and `Notification` to the library
And `Application` seems superfluous.

Full code:
```java
        fr.jcgay.notification.Notifier notifier = new SendNotification()
                .setApplication(Application.builder()
                        .id("an-id")
                        .name("a-name")
                        .icon(buildIcon())
                        .build())
                .initNotifier();

        try {
            notifier.send(Notification.builder()
                    .title("Title")
                    .message("Message")
                    .icon(buildIcon())
                    .build());
        } finally {
            notifier.close();
        }
```

What I expected:
```java
        try {
                    fr.jcgay.notification.Notifier notifier = new SendNotification().send(Notification.builder()
                    .title("Title")
                    .message("Message")
                    .icon(buildIcon())
                    .build());
        } finally {
            notifier.close();
        }
```

Technically, why `Application` is required ?

**Comment by jcgay** [comment]
It's needed by some notifiers when you can set a base configuration for all notifications across the same application.

For example you need to register an application before sending notification with `Growl` and `Snarl`.  You can then customize your notification directly in `Growl` or `Snarl`.  
It is also used by some others to display different icons in notifications (one global for your application and one specific for your notification). This is the case with `terminal-notifier` and `AnyBar`.

But I think I could provide a default application when one does not want to customize it.

Does it make sense ?

**Comment by tomsquest** [comment]
Yes, it perfectly make senses. And indeed, this is what the CLI does by setting the app's ID/name from the path (if I remember well).

**Comment by jcgay** [comment]
The CLI just registered itself as an `Application`, it's not dynamically set from the path.  
I'll give it a try, thx for the feeback!
